# Generated by Django 5.2 on 2025-04-04 17:27

from django.db import migrations, models
from django.db.models.deletion import CASCADE
from django.db.models.fields import uuid
from apps.iam.enums.UserAliasType import UserAliasType
from apps.iam.migrations.common import utils

(is_active_forwards) = utils.generate_default_boolean_field_migration('"authentication"."user_alias"', 'is_active', False)

class Migration(migrations.Migration):
   
    initial = True

    dependencies = [
        ('iam', '0002_create_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlias',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('type', models.CharField(max_length=100, choices=UserAliasType.choices)),
                ('value', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=CASCADE, to='iam.UserModel')),
            ],
            options={
                'db_table':  '"authentication"."user_alias"',
                'managed': True
            },
        ),
        *utils.add_base_field_default('"authentication"."user_alias"'),
    ]
